downgrade to july-2026 release, bump redis
Current release is broken and fails with:

  LoadError: Error loading the 'redis' Action Cable pubsub adapter.
  Missing a gem it depends on? can't activate redis (>= 4, < 6),
  already activated redis-6.0.0. Make sure all dependencies are added to Gemfile.

Signed-off-by: Jakub Sokołowski <jakub@status.im>